version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - python3 -m venv /root/venv
      - . /root/venv/bin/activate
      - pip3 install --no-cache-dir -r requirements.txt
cache:
  paths:
    - '/root/venv/**/*'
    - '/root/.cache/pip/**/*'
    - '/root/.cache/pypoetry/virtualenvs/**/*'

artifacts:
  files:
    - '**/*'